const router = require("express").Router();

router.use("/auth", require("./auth.route"));
router.use("/user", require("./userRoutes"));
// router.use("/Conection", require("./conectionRoutes"));
router.use("/astrologer", require("./astrologer"));
router.use("/horoscope", require("./horoScopeRoute"));
router.use("/kundli", require("./kundliRourer"));
router.use("/order", require("./order"));
router.use("/product", require("./product"));
router.use("/astrocallhistory", require("./astrocallRouter"));
router.use("/discount", require("./discountRouter"));
router.use("/chat", require("./chatHistory"));
// router.use("/agora", require("./agoreRouter."));
router.use("/api/v1", require("./product-category"));
router.use("/api/v1", require("./profile.route"));
router.use("/api/v1", require("./followRoutes"));
router.use("/api/v1", require("./blog.route"));
router.use("/api/v1", require("./privacy.route"));
router.use("/admin", require("./admin"));
router.use("/banner", require("./bannerRoutes"));
router.use("/api/v1", require("./notificationRouter"));
router.use("/api/v1", require("./supportRoute"));
router.use("/", require("./terms.route"));
router.use("/api/v1/wallet", require("./wallet.route"));
router.use("/api/v1", require("./astrologerFee"));
router.use("/api/v1", require("./astrologerLiveSchedule"));
router.use("/api/v1", require("./birthDetails.route"));
router.use("/api/v1/app-feedbacks", require("./feedback-app.route"));
router.use("/api/v1", require("./astrology.route"));
router.use("/api/v1", require("./astroStatus"));
router.use("/api/v1", require("./order"));
module.exports = router;
